// AUTO-GENERATED by scripts/sanctuary_assets/build_manifest.mjs -- DO NOT EDIT.
// Source of truth: scripts/sanctuary_assets/assets.json
// Regenerate: cd scripts/sanctuary_assets && npm run manifest

import type { SanctuaryZoneId } from "@/src/api/sanctuary";

export type SanctuaryElementAsset = {
  /** Metro asset module id (the value of require("….glb")). */
  module: number;
  zone: SanctuaryZoneId | null;
  anchor: string | null;
  scale: number;
  rotationY: number;
  animations: readonly string[];
};

export type SanctuarySceneryAsset = SanctuaryElementAsset & {
  /** Renders once the zone's depth_tier reaches this threshold. */
  tierMin: number;
};

/** Content icon key (content/sanctuary/*.json) -> placed model. */
export const SANCTUARY_ELEMENT_ASSETS: Record<string, SanctuaryElementAsset> = {

};

/** Zone tier-dressing layers, keyed by entry name. */
export const SANCTUARY_SCENERY_ASSETS: Record<string, SanctuarySceneryAsset> = {
  "bush": {
    module: require("../../assets/sanctuary/models/meadow/bush.glb") as number,
    zone: "meadow",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "bush-large": {
    module: require("../../assets/sanctuary/models/meadow/bush-large.glb") as number,
    zone: "meadow",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 3,
  },
  "flower-purple": {
    module: require("../../assets/sanctuary/models/meadow/flower-purple.glb") as number,
    zone: "meadow",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 3,
  },
  "flower-red": {
    module: require("../../assets/sanctuary/models/meadow/flower-red.glb") as number,
    zone: "meadow",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 5,
  },
  "flower-yellow": {
    module: require("../../assets/sanctuary/models/meadow/flower-yellow.glb") as number,
    zone: "meadow",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 3,
  },
  "mushroom-group": {
    module: require("../../assets/sanctuary/models/woodland/mushroom-group.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 5,
  },
  "pine-round": {
    module: require("../../assets/sanctuary/models/woodland/pine-round.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "pine-tall": {
    module: require("../../assets/sanctuary/models/woodland/pine-tall.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 3,
  },
  "rock-large-a": {
    module: require("../../assets/sanctuary/models/shared/rock-large-a.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "rock-large-c": {
    module: require("../../assets/sanctuary/models/shared/rock-large-c.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "rock-small-a": {
    module: require("../../assets/sanctuary/models/shared/rock-small-a.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "rock-small-d": {
    module: require("../../assets/sanctuary/models/shared/rock-small-d.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "rock-tall-b": {
    module: require("../../assets/sanctuary/models/shared/rock-tall-b.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "stump-round": {
    module: require("../../assets/sanctuary/models/woodland/stump-round.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 3,
  },
  "tree-default": {
    module: require("../../assets/sanctuary/models/woodland/tree-default.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "tree-detailed": {
    module: require("../../assets/sanctuary/models/woodland/tree-detailed.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 3,
  },
  "tree-oak": {
    module: require("../../assets/sanctuary/models/woodland/tree-oak.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
  "tree-thin": {
    module: require("../../assets/sanctuary/models/woodland/tree-thin.glb") as number,
    zone: "woodland",
    anchor: null,
    scale: 1,
    rotationY: 0,
    animations: [],
    tierMin: 1,
  },
};
