// GENERATED BY THE SANCTUARY ART PIPELINE -- STUB UNTIL D5.
// scripts/sanctuary_assets will emit the real sprite-atlas manifest here
// once the 2.5D sprite renders land; hand-edits will be overwritten.

import type { SanctuaryZoneId } from "@/src/api/sanctuary";

export type SanctuaryElementSprite = {
  /** Metro asset module id (the value of require("….png")). */
  module: number;
  zone: SanctuaryZoneId | null;
  /** Foot anchor within the sprite, 0..1 from the top-left (null = bottom-center). */
  anchor: { x: number; y: number } | null;
  /** Authored semantic scale multiplier (1 = drawn at native sprite size). */
  scale: number;
};

export type SanctuaryScenerySprite = SanctuaryElementSprite & {
  /** Renders once the zone's depth_tier reaches this threshold. */
  tierMin: number;
};

/** Content icon key (content/sanctuary/*.json) -> placed sprite. */
export const SANCTUARY_ELEMENT_SPRITES: Record<string, SanctuaryElementSprite> =
  {};

/** Zone tier-dressing sprites, keyed by entry name. */
export const SANCTUARY_SCENERY_SPRITES: Record<string, SanctuaryScenerySprite> =
  {};
