"""GCS signed-URL generation for photo upload.

Cloud Run runs under Application Default Credentials (the runtime SA), which
has no private key. V4 signed URLs are generated by delegating the actual
signing to IAM `signBlob` against the SA itself -- this requires the runtime
SA to have `roles/iam.serviceAccountTokenCreator` on itself (codified in
`infra-gcp/main.tf` as `google_service_account_iam_member.api_token_creator_self`).
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Annotated, Any, Protocol, cast

import google.auth
import google.auth.transport.requests
from fastapi import Depends, Request
from google.cloud import storage


class SignedUrlGenerator(Protocol):
    """Photo bucket facade: signed-PUT URL generation + server-side reads.

    Named `SignedUrlGenerator` for backwards compatibility with PR #30; the
    role expanded in PR #38 (Phase 7) to include `fetch_object_bytes` for
    the identify-endpoint's iNat CV call. Tests can implement either or
    both methods on a stub depending on which paths the test exercises.
    """

    def generate_put_url(
        self,
        *,
        bucket: str,
        object_name: str,
        content_type: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        """Return `(signed_url, expires_at)` for a single PUT.

        The URL is bound to `content_type` -- the client MUST PUT with a
        matching `Content-Type` header or the upload will be rejected.
        """
        ...

    def fetch_object_bytes(self, *, bucket: str, object_name: str) -> bytes:
        """Read a photo's raw bytes from GCS.

        Used by the iNat identify endpoint to feed the kid's photo into
        the CV call. Server-side download keeps the iNat token off the
        mobile binary and lets us cache responses by photo_id later.
        """
        ...

    def copy_object(
        self,
        *,
        src_bucket: str,
        src_object: str,
        dst_bucket: str,
        dst_object: str,
    ) -> None:
        """Copy a GCS object server-side. Used by the moderation worker
        to move `pending/<id>.jpg` to `observations/<id>.jpg` or
        `quarantine/<id>.jpg` per ADR 0009 + `docs/moderation.md`."""
        ...

    def delete_object(self, *, bucket: str, object_name: str) -> None:
        """Delete a GCS object. Paired with `copy_object` to implement a
        move (copy then delete) on the moderation hot path."""
        ...

    def generate_get_url(
        self,
        *,
        bucket: str,
        object_name: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        """Return `(signed_url, expires_at)` for a single GET.

        Used by the review-queue UI to render quarantined photos for
        teachers, and by the My Observations list to render clean photos
        for kids. Same IAM-signing pattern as `generate_put_url`.
        """
        ...


class GcsSignedUrlGenerator:
    """ADC-backed implementation. Uses IAM signBlob, no private key required."""

    def __init__(self) -> None:
        self._client = storage.Client()
        # google-auth returns a polymorphic Credentials subclass at runtime
        # (ComputeEngineCredentials on Cloud Run); the base class doesn't
        # declare service_account_email or a typed refresh, so we treat the
        # handle as Any.
        creds, _project = google.auth.default(
            scopes=["https://www.googleapis.com/auth/cloud-platform"],
        )
        self._credentials: Any = creds

    def generate_put_url(
        self,
        *,
        bucket: str,
        object_name: str,
        content_type: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        # Refresh is a no-op when the cached token is still valid; on Cloud Run
        # this hits the metadata server (local + fast).
        self._credentials.refresh(google.auth.transport.requests.Request())

        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        url = blob.generate_signed_url(
            version="v4",
            expiration=expires_in,
            method="PUT",
            content_type=content_type,
            service_account_email=self._credentials.service_account_email,
            access_token=self._credentials.token,
        )
        expires_at = datetime.now(UTC) + expires_in
        return cast(str, url), expires_at

    def fetch_object_bytes(self, *, bucket: str, object_name: str) -> bytes:
        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        return cast(bytes, blob.download_as_bytes())

    def copy_object(
        self,
        *,
        src_bucket: str,
        src_object: str,
        dst_bucket: str,
        dst_object: str,
    ) -> None:
        src_bucket_obj = self._client.bucket(src_bucket)
        src_blob = src_bucket_obj.blob(src_object)
        dst_bucket_obj = self._client.bucket(dst_bucket)
        src_bucket_obj.copy_blob(src_blob, dst_bucket_obj, new_name=dst_object)

    def delete_object(self, *, bucket: str, object_name: str) -> None:
        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        blob.delete()

    def generate_get_url(
        self,
        *,
        bucket: str,
        object_name: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        # Same metadata-server refresh pattern as generate_put_url.
        self._credentials.refresh(google.auth.transport.requests.Request())
        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        url = blob.generate_signed_url(
            version="v4",
            expiration=expires_in,
            method="GET",
            service_account_email=self._credentials.service_account_email,
            access_token=self._credentials.token,
        )
        expires_at = datetime.now(UTC) + expires_in
        return cast(str, url), expires_at


def get_signed_url_generator(request: Request) -> SignedUrlGenerator:
    """Pull the generator off `app.state` so tests can inject a fake."""
    generator = getattr(request.app.state, "signed_url_generator", None)
    if generator is None:
        generator = GcsSignedUrlGenerator()
        request.app.state.signed_url_generator = generator
    return cast(SignedUrlGenerator, generator)


SignedUrlGeneratorDep = Annotated[SignedUrlGenerator, Depends(get_signed_url_generator)]
